### problem 1

*question:*
$$A=\begin{bmatrix}-1&2&3\\
4&-1&6\\
7&8&-9
\end{bmatrix},B=\begin{bmatrix}0&2&1\\
0&2&-8\\
2&9&-1
\end{bmatrix}$$

*answer:*
$$
\begin{bmatrix}(-1*0)+(2*0)+(3*2)&(-1*2)+(2*2)+(3*9)&(-1*1)+(2*8)+(3*-1)\\
(4*0)+(-5*0)+(6*2)&(4*2)+(-5*2)+(6*9)&(4*1)+(-5*-8)+(6*-1)\\
(7*0)+(8*0)+(-9*2)&(7*2)+(8*2)+(-9*2)&(7*1)+(8*-8)+(-9*-1)
\end{bmatrix}
$$

**final answer**
$$
\begin{bmatrix}
6&29&-20\\
12&52&38\\
-18&12&-48
\end{bmatrix}
$$

In [2]:
# problem 2
import   numpy   as  np 
a_ndarray = np.array([[-1  ,  2  ,  3  ], [  4  ,-5  ,  6  ], [  7  ,  8  ,-9  ]]) 
b_ndarray = np.array([[  0  ,  2  ,  1  ], [  0  ,  2  ,-  8  ], [  2  ,  9  ,-1 ]])
answer_1 = np.matmul(a_ndarray,b_ndarray)
print(answer_1)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [8]:
# problem 3
# answer_2 = np.empty([3,3])
# for row in range(a_ndarray.shape[0]):
#     for column in range(b_ndarray.shape[1]):
#         answer_2[row][column]=sum(a_ndarray[row,:]*b_ndarray[:,column])

answer_2 = (a_ndarray[0][0]*b_ndarray[0][0])+(a_ndarray[0][1]*b_ndarray[0][1])+(a_ndarray[0][2]*b_ndarray[2][0])
print(answer_2)

10


In [7]:
# problem 4
def calculate_matrix(a,b):
    answer_2_1 = np.empty([3,3])
    for row_1 in range(a.shape[0]):
        for column_1 in range(b.shape[1]):
            answer_2_1[row_1][column_1] = sum(a[row_1,:]*b[:,column_1])
    return answer_2_1
print(calculate_matrix(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [25]:
# problem 5
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
if(d_ndarray.shape[0]==e_ndarray.shape[1]):
    print(calculate_matrix(d_ndarray,e_ndarray))
else:
    print("this matrix can not be calculated")

this matrix can not be calculated


In [29]:
# problem 6
def calculate_matrix_2(a,b):
    if(a.shape[0]==b.shape[1]):
        answer_2_1 = np.empty([3,3])
        for row_1 in range(a.shape[0]):
            for column_1 in range(b.shape[1]):
                answer_2[row_1][column_1]=sum(a[row_1,:]*b[:,column_1])
        return answer_2_1
    else:
        return "this matrix can be calculated"
print(calculate_matrix_2(d_ndarray,e_ndarray))

this matrix can be calculated


In [35]:
# problem 7
transposed_ndarray = np.transpose(e_ndarray)
print("after transpose {}".format(transposed_e_ndarray))
print("------------------------------")
print("solution {}".format(calculate_matrix_2(d_ndarray,transposed_ndarray)))

after transpose [[-9  6]
 [ 8 -5]
 [ 7  4]]
------------------------------
solution [[ 6. 29. 20.]
 [12. 52. 38.]
 [18. 51. 48.]]
